### ISSUE TITLE
Error if circles is disabled

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/related_resources#167]
```
An unhandled exception has been thrown:
OCP\AutoloadNotAllowedException: Autoload path not allowed: /var/www/html/apps/circles/lib/circlesmanager.php in /var/www/html/lib/autoloader.php:141
Stack trace:
#0 /var/www/html/lib/autoloader.php(166): OC\Autoloader->isValidPath('/var/www/html/a...')
#1 [internal function]: OC\Autoloader->load('OCA\\Circles\\Cir...')
#2 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(123): ReflectionClass->__construct('OCA\\Circles\\Cir...')
#3 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(142): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Circles\\Cir...')
#4 /var/www/html/lib/private/ServerContainer.php(171): OC\AppFramework\Utility\SimpleContainer->query('OCA\\Circles\\Cir...', true)
#5 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(66): OC\ServerContainer->query('OCA\\Circles\\Cir...')
#6 /var/www/html/lib/public/Server.php(55): OC\AppFramework\Utility\SimpleContainer->get('OCA\\Circles\\Cir...')
#7 /var/www/html/apps-extra/related_resources/lib/Service/RelatedService.php(98): OCP\Server::get('OCA\\Circles\\Cir...')
#8 [internal function]: OCA\RelatedResources\Service\RelatedService->__construct(Object(OC\App\AppManager), Object(OC\Memcache\Factory), Object(OC\AppFramework\ScopedPsrLogger), Object(OCA\RelatedResources\Service\ConfigService))
#9 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(117): ReflectionClass->newInstanceArgs(Array)
#10 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(125): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#11 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(142): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\RelatedReso...')
#12 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(480): OC\AppFramework\Utility\SimpleContainer->query('OCA\\RelatedReso...')
#13 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(452): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\RelatedReso...')
#14 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(98): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\RelatedReso...', true)
#15 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
#16 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(117): array_map(Object(Closure), Array)
#17 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(125): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#18 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(142): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\RelatedReso...')
#19 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(480): OC\AppFramework\Utility\SimpleContainer->query('OCA\\RelatedReso...')
#20 /var/www/html/lib/private/ServerContainer.php(155): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\RelatedReso...')
#21 /var/www/html/lib/private/Console/Application.php(220): OC\ServerContainer->query('OCA\\RelatedReso...')
#22 /var/www/html/lib/private/Console/Application.php(130): OC\Console\Application->loadCommandsFromInfoXml(Array)
#23 /var/www/html/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/html/occ(11): require_once('/var/www/html/c...')
#25 {main}~/repos/nextcloud/server
```

@ArtificialOwl

**Comment by ArtificialOwl** [comment]
cannot reproduce; which version of NC ?

**Comment by juliushaertl** [comment]
Latest master from server + related resources (aeaf44a)
